### ISSUE TITLE
smooth_sampler ops build error

### ISSUE THREAD

**Issue by dyy0205** [Nightmare-n/UniPAD#4]
Hi, thank you for sharing this excellent work! When i try to install this project using `python setup.py develop --user`, i met this compilation error
<img width="871" alt="截屏2023-12-19 上午10 33 52" src="https://github.com/Nightmare-n/UniPAD/assets/49671641/7015459e-ece1-4fce-8215-39dd15b73c48">
I wonder how can i solve this errors, hope for your reply!!

**Comment by Nightmare-n** [comment]
Hi, which pytorch version do you use?

**Comment by dyy0205** [comment]
> Hi, which pytorch version do you use?

torch==1.10.2+cu111, torchvision==0.11.3+cu111, torch-scatter==2.0.9

**Comment by Nightmare-n** [comment]
The error may be caused by different pytorch verison. You could try to replace the old function according to [here](https://github.com/pytorch/pytorch/blob/v1.10.1/aten/src/ATen/native/cuda/GridSampler.cu). Or you could upgrade pytorch version and directly use [this](https://github.com/OpenGVLab/PonderV2/tree/main/libs/smooth-sampler) for pytorch>=1.11.
